# Site settings
title: Savvy Coders | Intro to Web Development
email: info@savvycoders.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to Code with HTML, CSS, and JavaScript in Nashville, TN and St. Louis, MO.
baseurl: ""
url: "https://savvycoders.com" # the base hostname & protocol for your site
exclude: ["node_modules","theme","public","gulpfile.js","build.sh","package.json","README.md"]
include: [".htaccess"]
twitter_username: SavvyCoders
github_username:  NAlexPear

# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title/

# Prose settings
prose:
    rooturl: "_drafts"
    media: "theme/images"
    metadata:
    _drafts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          value: "title"
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
